---
version: 1.0.0
client:
  organization: org1

  logging:
    level: info

  cryptoconfig:
    path: ${CRYPTO_CONFIG_BASE_PATH}

  credentialStore:
    path: "/tmp/state-store"

    cryptoStore:
      path: /tmp/msp

  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     level: 256

  tlsCerts:
    systemCertPool: true

    client:
      key:
        path: ${CRYPTO_CONFIG_BASE_PATH}/peerOrganizations/org1.example.com/users/Admin@org1.example.com/tls/client.key
      cert:
        path: ${CRYPTO_CONFIG_BASE_PATH}/peerOrganizations/org1.example.com/users/Admin@org1.example.com/tls/client.crt

channels:

  _default:

    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    policies:
      discovery:
        maxTargets: 2
        retryOpts:
          attempts: 4
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
      selection:
        SortingStrategy: BlockHeightPriority
        Balancer: RoundRobin
        BlockHeightLagThreshold: 5
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0

      eventService:
        resolverStrategy: PreferOrg
        balancer: RoundRobin
        blockHeightLagThreshold: 2
        reconnectBlockHeightLagThreshold: 5
        peerMonitorPeriod: 3s

  channel1:
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  org1:
    mspid: Org1MSP

    cryptoPath:  peerOrganizations/org1.example.com/users/{username}@org1.example.com/msp

    peers:
      - peer0.org1.example.com

    certificateAuthorities:
      - ca.org1.example.com
      - tlsca.org1.example.com
    
  ordererorg:
      mspID: OrdererMSP

      cryptoPath: ordererOrganizations/example.com/users/{username}@example.com/msp


orderers:
  _default:
    grpcOptions:
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false

  orderer.example.com:
    url: orderer.example.com:7050

    tlsCACerts:
      path: ${CRYPTO_CONFIG_BASE_PATH}/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem

peers:
  _default:
    grpcOptions:
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false

  peer0.org1.example.com:
    url: peer0.org1.example.com:7051

    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com

    tlsCACerts:
      # Certificate location absolute path
      path: ${CRYPTO_CONFIG_BASE_PATH}/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem


certificateAuthorities:
  ca.org1.example.com:
    url: https://ca.org1.example.com:7054
    grpcOptions:
      ssl-target-name-override: ca.org1.example.com
    tlsCACerts:
      path: ${CRYPTO_CONFIG_BASE_PATH}/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
      client:
        key:
          path: ${CRYPTO_CONFIG_BASE_PATH}/peerOrganizations/org1.example.com/users/Admin@org1.example.com/tls/client.key
        cert:
          path: ${CRYPTO_CONFIG_BASE_PATH}/peerOrganizations/org1.example.com/users/Admin@org1.example.com/tls/client.crt

    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca.org1.example.com
  tlsca.org1.example.com:
    url: https://ca.org1.example.com:7154
    tlsCACerts:
      path: ${CRYPTO_CONFIG_BASE_PATH}/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
      client:
        key:
          path: ${CRYPTO_CONFIG_BASE_PATH}/peerOrganizations/org1.example.com/users/Admin@org1.example.com/tls/client.key
        cert:
          path: ${CRYPTO_CONFIG_BASE_PATH}/peerOrganizations/org1.example.com/users/Admin@org1.example.com/tls/client.crt

    registrar:
      enrollId: admin2
      enrollSecret: adminpw2
    caName: tlsca.org1.example.com

entityMatchers:
  # 在 hosts 中写入
  # 127.0.0.1 peer0.org1.example.com                      
  # 127.0.0.1 orderer.example.com 
  peer:
    - pattern: (\w+).org1.example.(\w+):(\d+)
      urlSubstitutionExp: grpcs://${1}.org1.example.${2}:${3}
      sslTargetOverrideUrlSubstitutionExp: peer0.org1.example.com
      mappedHost: peer0.org1.example.com

    ###
    - pattern: (\w+).org1.example.com:(\d+)
      urlSubstitutionExp: ${1}.org1.example.com:${2}
      sslTargetOverrideUrlSubstitutionExp: ${1}.org1.example.com
      mappedHost: peer0.org1.example.com

    ###
    - pattern: (\w+).org1.example.(\w+)
      urlSubstitutionExp: peer0.org1.example.com:7051
      sslTargetOverrideUrlSubstitutionExp: peer0.org1.example.com
      mappedHost: peer0.org1.example.com

    ###
    - pattern: (\w+).example1.(\w+):(\d+)
      urlSubstitutionExp: ${1}.org1.example.${2}:${3}
      sslTargetOverrideUrlSubstitutionExp: ${1}.org1.example.${2}
      mappedHost: peer0.org1.example.com

    ###
    - pattern: (\w+).org1.example.(\w+):(\d+)
      urlSubstitutionExp: peer0.org1.example.com:7051
      sslTargetOverrideUrlSubstitutionExp: peer0.org1.example.com
      mappedHost: peer0.org1.example.com

  # 实际环境下，可能每个组织都有其各种的 orderer，需对应修改
  orderer:
    - pattern: (\w+).example.(\w+)
      urlSubstitutionExp: orderer.example.com:7050
      sslTargetOverrideUrlSubstitutionExp: orderer.example.com
      mappedHost: orderer.example.com

  # 实际环境下，urlSubstitutionExp 使用真实 ip 或域名代替 localhost
  certificateAuthority:
    # - pattern: (\w+).org1.example.(\w+)
    #   urlSubstitutionExp: http://localhost:7054
    #   sslTargetOverrideUrlSubstitutionExp: ca.example.com
    #   mappedHost: ca.org1.example.com


operations:
  listenAddress: 127.0.0.1:6060
  tls:
    # TLS enabled
    enabled: false
    cert:
      file:

    key:
      file:

    clientAuthRequired: false

    clientRootCAs:
      files: []

metrics:
  provider: prometheus

  statsd:
    network: udp
    address: 127.0.0.1:6125
    writeInterval: 10s
    prefix: